sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install tox

script:
  - |
    set -x
    TOX_PY="py${TRAVIS_PYTHON_VERSION/./}"
    tox
    set +x

notifications:
  email: false
